#NAME: Lawrence Chen
#EMAIL: lawrencechen98@gmail.com
#ID: XXXXXXXXX

.SILENT:

default:
	gcc -Wall -Wextra -o lab1a -g lab1a.c

dist:
	tar -czvf lab1a-XXXXXXXXX.tar.gz lab1a.c README Makefile  

clean: 
	rm -f lab1a lab1a-XXXXXXXXX.tar.gz 
