#NAME: Lawrence Chen,Nityan Bhorde
#EMAIL: lawrencechen98@gmail.com,nityanbhorde21@g.ucla.edu
#ID: 704767754,904793498

default: lab3a.c
	gcc -Wall -Wextra -lm -g lab3a.c -o lab3a

clean:
	rm -rf lab3a lab3a-704767754.tar.gz 

dist:
	tar -czvf lab3a-704767754.tar.gz README Makefile lab3a.c ext2_fs.h
